### ISSUE TITLE
GNOME 3.24 Configuration dialog error

### ISSUE THREAD

**Issue by nobeh** [vibou/vibou.gTile#66]
Setup is GNOME 3.24 Ubuntu 17.04.

When clicking on Configuration in GNOME Tweak Tool:

```
TypeError: redeclaration of formal parameter iter

Stack trace:
  Application<._getExtensionPrefsModule@resource:///org/gnome/shell/extensionPrefs/main.js:74:13
  wrapper@resource:///org/gnome/gjs/modules/lang.js:178:22
  Application<._selectExtension@resource:///org/gnome/shell/extensionPrefs/main.js:89:31
  wrapper@resource:///org/gnome/gjs/modules/lang.js:178:22
  Application<._onCommandLine@resource:///org/gnome/shell/extensionPrefs/main.js:243:17
  wrapper@resource:///org/gnome/gjs/modules/lang.js:178:22
  main@resource:///org/gnome/shell/extensionPrefs/main.js:399:5
  @<main>:1:49
  
```

**Comment by nobeh** [comment]
Dups #58

**Comment by scherepanov** [comment]
It is fixed on my branch

**Comment by elpraga** [comment]
@vibou , is it going to be fixed in the official extension? The branch @scherepanov made works (even though I am not able to check the quality of the code).

Recently an official update came, but still with the configuration dialogue broken. 

Do you have any plans of fixing it?

**Comment by scherepanov** [comment]
I think @vibou abandoned this project, or lost interest in maintaining it.

For quality of code on scherepanov branch. That was my JS learning project. I added quite a few functionality and did some changes to existing code. Number of code lines almost doubled.
That would be interesting if you will check code and tell me what can be done better.

**Comment by elpraga** [comment]
hahahaha That would indeed be interesting, nevertheless also impossible. I no completely nothing about JS. 

Have you considered uploading your fork to exensions.gnome.org @scherepanov ?

**Comment by ghost** [comment]
Why do I still get this error (Ubuntu 17.04, Gnome Shell: 3.24.2)?
